
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kalra
 */
public class MAIN_APP_WINDOW extends javax.swing.JFrame {

    /**
     * Creates new form MAIN_APP_WINDOW
     */
    public MAIN_APP_WINDOW() {
        initComponents();
        
        jLabel_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png")));
    
        Border logo_border = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.black);
        jLabel_icon.setBorder(logo_border);
        
        Border name_border = BorderFactory.createMatteBorder(0, 0, 3, 0, Color.white);
        jLabel_name.setBorder(name_border);
        
        Border menu_items_border = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.yellow);
        jLabel_property.setBorder(menu_items_border);
        jLabel_type.setBorder(menu_items_border);
        jLabel_image.setBorder(menu_items_border);
        jLabel_owner.setBorder(menu_items_border);
        jLabel_client.setBorder(menu_items_border);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_icon = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_property = new javax.swing.JLabel();
        jLabel_owner = new javax.swing.JLabel();
        jLabel_image = new javax.swing.JLabel();
        jLabel_type = new javax.swing.JLabel();
        jLabel_client = new javax.swing.JLabel();
        jLabel_sale = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 213, 183));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel_icon.setBackground(new java.awt.Color(51, 153, 255));
        jLabel_icon.setOpaque(true);

        jLabel_name.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("MyApp");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_name)
                .addGap(25, 25, 25))
        );

        jLabel_property.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_property.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_property.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_property.setText("Property");
        jLabel_property.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_property.setOpaque(true);
        jLabel_property.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_propertyMouseExited(evt);
            }
        });

        jLabel_owner.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_owner.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_owner.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_owner.setText("Owner");
        jLabel_owner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_owner.setOpaque(true);
        jLabel_owner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ownerMouseExited(evt);
            }
        });

        jLabel_image.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_image.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_image.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_image.setText("Property-Images");
        jLabel_image.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_image.setOpaque(true);
        jLabel_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_imageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_imageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_imageMouseExited(evt);
            }
        });

        jLabel_type.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_type.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_type.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_type.setText("Property-Type");
        jLabel_type.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_type.setOpaque(true);
        jLabel_type.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_typeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_typeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_typeMouseExited(evt);
            }
        });

        jLabel_client.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_client.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_client.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_client.setText("Client");
        jLabel_client.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_client.setOpaque(true);
        jLabel_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_clientMouseExited(evt);
            }
        });

        jLabel_sale.setBackground(new java.awt.Color(102, 102, 102));
        jLabel_sale.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel_sale.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_sale.setText("Sale");
        jLabel_sale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_sale.setOpaque(true);
        jLabel_sale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_saleMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_property, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_owner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_client, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_sale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_property, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_type, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_image, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_owner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_client, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_sale, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 750, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_propertyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseEntered
        // TODO add your handling code here:
        jLabel_property.setBackground(Color.white);
        jLabel_property.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_propertyMouseEntered

    private void jLabel_propertyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseExited
        // TODO add your handling code here:
        jLabel_property.setBackground(new Color(102, 102, 102));
        jLabel_property.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_propertyMouseExited

    private void jLabel_typeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_typeMouseEntered
        // TODO add your handling code here:
        jLabel_type.setBackground(Color.white);
        jLabel_type.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_typeMouseEntered

    private void jLabel_typeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_typeMouseExited
        // TODO add your handling code here:
        jLabel_type.setBackground(new Color(102, 102, 102));
        jLabel_type.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_typeMouseExited

    private void jLabel_imageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_imageMouseEntered
        // TODO add your handling code here:
        jLabel_image.setBackground(Color.white);
        jLabel_image.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_imageMouseEntered

    private void jLabel_imageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_imageMouseExited
        // TODO add your handling code here:
        jLabel_image.setBackground(new Color(102, 102, 102));
        jLabel_image.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_imageMouseExited

    private void jLabel_ownerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseEntered
        // TODO add your handling code here:
        jLabel_owner.setBackground(Color.white);
        jLabel_owner.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_ownerMouseEntered

    private void jLabel_ownerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseExited
        // TODO add your handling code here:
        jLabel_owner.setBackground(new Color(102, 102, 102));
        jLabel_owner.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_ownerMouseExited

    private void jLabel_clientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseEntered
        // TODO add your handling code here:
        jLabel_client.setBackground(Color.white);
        jLabel_client.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_clientMouseEntered

    private void jLabel_clientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseExited
        // TODO add your handling code here:
        jLabel_client.setBackground(new Color(102, 102, 102));
        jLabel_client.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_clientMouseExited

    private void jLabel_typeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_typeMouseClicked
        // TODO add your handling code here:
        Property_Type typeform = new Property_Type();
        typeform.setVisible(true);
        typeform.pack();
        typeform.setLocationRelativeTo(null);
        typeform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_typeMouseClicked

    private void jLabel_ownerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ownerMouseClicked
        // TODO add your handling code here:
        Owner_Window ownerform = new Owner_Window();
        ownerform.setVisible(true);
        ownerform.pack();
        ownerform.setLocationRelativeTo(null);
        ownerform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_ownerMouseClicked

    private void jLabel_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_clientMouseClicked
        // TODO add your handling code here:
        Client_Window clientform = new Client_Window();
        clientform.setVisible(true);
        clientform.pack();
        clientform.setLocationRelativeTo(null);
        clientform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_clientMouseClicked

    private void jLabel_propertyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_propertyMouseClicked
        // TODO add your handling code here:
        Property_window propertyform = new Property_window();
        propertyform.setVisible(true);
        propertyform.pack();
        propertyform.setLocationRelativeTo(null);
        propertyform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_propertyMouseClicked

    private void jLabel_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_imageMouseClicked
        // TODO add your handling code here:
        Property_Images_Window propertyImage = new Property_Images_Window();
        propertyImage.setVisible(true);
        propertyImage.pack();
        propertyImage.setLocationRelativeTo(null);
        propertyImage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_imageMouseClicked

    private void jLabel_saleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseClicked
        // TODO add your handling code here:
        Sale_Window saleform = new Sale_Window();
        saleform.setVisible(true);
        saleform.pack();
        saleform.setLocationRelativeTo(null);
        saleform.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jLabel_saleMouseClicked

    private void jLabel_saleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseEntered
        // TODO add your handling code here:
        jLabel_sale.setBackground(Color.white);
        jLabel_sale.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jLabel_saleMouseEntered

    private void jLabel_saleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_saleMouseExited
        // TODO add your handling code here:
        jLabel_sale.setBackground(new Color(102, 102, 102));
        jLabel_sale.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_saleMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN_APP_WINDOW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN_APP_WINDOW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_client;
    private javax.swing.JLabel jLabel_icon;
    private javax.swing.JLabel jLabel_image;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_owner;
    private javax.swing.JLabel jLabel_property;
    private javax.swing.JLabel jLabel_sale;
    private javax.swing.JLabel jLabel_type;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
