
import java.awt.Color;
import java.util.HashMap;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kalra
 */
public class Property_window extends javax.swing.JFrame {

    /**
     * Creates new form Property_window
     */
    P_TYPE type = new P_TYPE();
    HashMap<String, Integer> map = type.getTypeMap();
    
    public Property_window() {
        initComponents();
        Border title_label_border = BorderFactory.createMatteBorder(0, 0, 3, 0, new Color(26,138,32));
        jPanel_title2.setBorder(title_label_border);
        
        bindCombo();
    }

    //populating jcombobox
    public void bindCombo(){
        for(String s : map.keySet()){
            jComboBox_type.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel_title2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_addr = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jTextField_sqft = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ownerid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_price = new javax.swing.JTextField();
        jButton_Search = new javax.swing.JButton();
        jComboBox_type = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jSpinner_bathrooms = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinner_bedrooms = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinner_age = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_desc = new javax.swing.JTextArea();
        jCheckBox_pool = new javax.swing.JCheckBox();
        jCheckBox_balcony = new javax.swing.JCheckBox();
        jCheckBox_backyard = new javax.swing.JCheckBox();
        jCheckBox_garage = new javax.swing.JCheckBox();
        jButton_show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(75, 192, 18));

        jPanel_title2.setBackground(new java.awt.Color(65, 160, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Property");

        javax.swing.GroupLayout jPanel_title2Layout = new javax.swing.GroupLayout(jPanel_title2);
        jPanel_title2.setLayout(jPanel_title2Layout);
        jPanel_title2Layout.setHorizontalGroup(
            jPanel_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_title2Layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_title2Layout.setVerticalGroup(
            jPanel_title2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_title2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Type:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Age of the House:");

        jTextField_id.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButton_edit.setBackground(new java.awt.Color(0, 153, 255));
        jButton_edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_edit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_edit.setText("Edit");
        jButton_edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setBackground(new java.awt.Color(255, 51, 51));
        jButton_remove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_remove.setForeground(new java.awt.Color(255, 255, 255));
        jButton_remove.setText("Remove");
        jButton_remove.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(51, 255, 51));
        jButton_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_add.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add.setText("Add");
        jButton_add.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jTextArea_addr.setColumns(20);
        jTextArea_addr.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jTextArea_addr.setRows(5);
        jScrollPane2.setViewportView(jTextArea_addr);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Square Feet:");

        jTextField_sqft.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Owner ID:");

        jTextField_ownerid.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Price(INR):");

        jTextField_price.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButton_Search.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Search.setText("Search");
        jButton_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SearchActionPerformed(evt);
            }
        });

        jComboBox_type.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Address:");

        jSpinner_bathrooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Bedrooms:");

        jSpinner_bedrooms.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel11.setText("Bathrooms:");

        jSpinner_age.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Description:");

        jTextArea_desc.setColumns(20);
        jTextArea_desc.setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N
        jTextArea_desc.setRows(5);
        jScrollPane3.setViewportView(jTextArea_desc);

        jCheckBox_pool.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_pool.setText("Pool");

        jCheckBox_balcony.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_balcony.setText("Balcony");
        jCheckBox_balcony.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_balconyActionPerformed(evt);
            }
        });

        jCheckBox_backyard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_backyard.setText("Backyard");

        jCheckBox_garage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCheckBox_garage.setText("Garage");

        jButton_show.setBackground(new java.awt.Color(153, 0, 153));
        jButton_show.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_show.setForeground(new java.awt.Color(255, 255, 255));
        jButton_show.setText("Show Properties");
        jButton_show.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_title2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 104, Short.MAX_VALUE)
                        .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jButton_show, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(122, 122, 122))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_ownerid, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_sqft, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)))
                                .addGap(120, 120, 120)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSpinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSpinner_bedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSpinner_bathrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_pool)
                            .addComponent(jCheckBox_backyard)
                            .addComponent(jCheckBox_balcony)
                            .addComponent(jCheckBox_garage))))
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel_title2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_type, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox_balcony, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_sqft, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_pool, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_ownerid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner_bedrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner_bathrooms, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_backyard, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jCheckBox_garage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        try{
            int id = Integer.valueOf(jTextField_id.getText());
            int type = map.get(jComboBox_type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_ownerid.getText());
            int squareFeet = Integer.valueOf(jTextField_sqft.getText());
            int bedrooms = Integer.valueOf(jSpinner_bedrooms.getValue().toString());
            int bathrooms = Integer.valueOf(jSpinner_bathrooms.getValue().toString());
            int age = Integer.valueOf(jSpinner_age.getValue().toString());
            boolean haveBalcony = false;
            boolean havePool = false;
            boolean haveBackyard = false;
            boolean haveGarage = false;
            
            if (jCheckBox_balcony.isSelected()) haveBalcony = true;
            if (jCheckBox_pool.isSelected()) havePool = true;
            if (jCheckBox_backyard.isSelected()) haveBackyard = true;
            if (jCheckBox_garage.isSelected()) haveGarage = true;
            
            String price = jTextField_price.getText();
            String address = jTextArea_addr.getText();
            String desc = jTextArea_desc.getText();
            
            P_Property property = new P_Property(id, type, squareFeet, ownerId, price, address, bedrooms, bathrooms, age, haveBalcony, havePool, haveBackyard, haveGarage, desc);
            
            if(new P_Property().editProperty(property)){
                JOptionPane.showMessageDialog(null, "Property Data Updated", "Edit Property", 1);
            }
            else{
                JOptionPane.showMessageDialog(null, "Property data NOT Edited", "Edit Property", 2);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Error ", "Error", 0);
        }
        
    }//GEN-LAST:event_jButton_editActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:

        try{
            int id = Integer.valueOf(jTextField_id.getText());

            P_Property property = new P_Property();

            if (jTextField_id.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Enter the Property ID", "Empty ID", 2);
            }
            else{
                int yes_or_no = JOptionPane.showConfirmDialog(null, "Do You Want To Delete This Property?", "Delte property", JOptionPane.YES_NO_OPTION);

                if(yes_or_no == JOptionPane.YES_OPTION){
                    if(property.removeProperty(id)){
                        JOptionPane.showMessageDialog(null, "Property Data Deleted", "Delete property", 1);
                        jTextField_id.setText("");
                        jTextField_price.setText("");
                        jTextField_sqft.setText("");
                        jTextField_ownerid.setText("");                       
                        jTextArea_addr.setText("");
                        jTextArea_desc.setText("");
                        jComboBox_type.setSelectedIndex(0);
                        jSpinner_age.setValue(0);
                        jSpinner_bedrooms.setValue(0);
                        jSpinner_bathrooms.setValue(0);
                        jCheckBox_pool.setSelected(false);
                        jCheckBox_balcony.setSelected(false);
                        jCheckBox_backyard.setSelected(false);
                        jCheckBox_garage.setSelected(false);
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Operation Failed", "Delete Property", 2);
                    }
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Enter a Valid Property ID ", "Invalid ID", 0);
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // TODO add your handling code here:
        try{
            int type = map.get(jComboBox_type.getSelectedItem().toString());
            int ownerId = Integer.valueOf(jTextField_ownerid.getText());
            int squareFeet = Integer.valueOf(jTextField_sqft.getText());
            int bedrooms = Integer.valueOf(jSpinner_bedrooms.getValue().toString());
            int bathrooms = Integer.valueOf(jSpinner_bathrooms.getValue().toString());
            int age = Integer.valueOf(jSpinner_age.getValue().toString());
            boolean haveBalcony = false;
            boolean havePool = false;
            boolean haveBackyard = false;
            boolean haveGarage = false;
            
            if (jCheckBox_balcony.isSelected()) haveBalcony = true;
            if (jCheckBox_pool.isSelected()) havePool = true;
            if (jCheckBox_backyard.isSelected()) haveBackyard = true;
            if (jCheckBox_garage.isSelected()) haveGarage = true;
            
            String price = jTextField_price.getText();
            String address = jTextArea_addr.getText();
            String desc = jTextArea_desc.getText();
            
            P_Property property = new P_Property(0, type, squareFeet, ownerId, price, address, bedrooms, bathrooms, age, haveBalcony, havePool, haveBackyard, haveGarage, desc);
            
            if(new P_Property().addNewProperty(property)){
                JOptionPane.showMessageDialog(null, "New Property Added to the System", "Add Property", 1);
            }
            else{
                JOptionPane.showMessageDialog(null, "Property NOT Added to the System", "Add Property", 1);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Error ", "Error", 0);
        }
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jCheckBox_balconyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_balconyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_balconyActionPerformed

    private void jButton_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showActionPerformed
        // TODO add your handling code here:
        Show_properties show_property = new Show_properties();
        show_property.setVisible(true);
        show_property.pack();
        show_property.setLocationRelativeTo(null);
        show_property.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton_showActionPerformed

    private void jButton_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SearchActionPerformed
        // TODO add your handling code here:
        try{
            int propertyId = Integer.valueOf(jTextField_id.getText());
            P_Property property = new P_Property().findProperty(propertyId);
            
            if(property != null){
                jTextArea_addr.setText(property.getAddress());
                jTextArea_desc.setText(property.getDesc());
                jTextField_price.setText(property.getPrice());
                jTextField_sqft.setText(String.valueOf(property.getSize()));
                jTextField_ownerid.setText(String.valueOf(property.getOwnerId()));
                
                for(Object type : map.keySet()){
                    if (map.get(type).equals(property.getType())) {
                        jComboBox_type.setSelectedItem(type);
                    }
                }
                
                jSpinner_bedrooms.setValue(property.getBedrooms());
                jSpinner_bathrooms.setValue(property.getBathrooms());
                jSpinner_age.setValue(property.getAge());
                if(property.isBalcony()) jCheckBox_balcony.setSelected(true);
                if(property.isBackyard()) jCheckBox_backyard.setSelected(true);
                if(property.isPool()) jCheckBox_pool.setSelected(true);
                if(property.isGarage()) jCheckBox_garage.setSelected(true);
            }
            else{
                JOptionPane.showMessageDialog(null, " Property Not Found ", "Error", 0);
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage() + " Error ", "Error", 0);
        }
    }//GEN-LAST:event_jButton_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Property_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Property_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Property_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Property_window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Property_window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Search;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_show;
    private javax.swing.JCheckBox jCheckBox_backyard;
    private javax.swing.JCheckBox jCheckBox_balcony;
    private javax.swing.JCheckBox jCheckBox_garage;
    private javax.swing.JCheckBox jCheckBox_pool;
    private javax.swing.JComboBox<String> jComboBox_type;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_title2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner_age;
    private javax.swing.JSpinner jSpinner_bathrooms;
    private javax.swing.JSpinner jSpinner_bedrooms;
    private javax.swing.JTextArea jTextArea_addr;
    private javax.swing.JTextArea jTextArea_desc;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_ownerid;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_sqft;
    // End of variables declaration//GEN-END:variables
}
